import React, { FC, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { searchRepos } from '@src/service/github';
import RepoList from '@src/components/RepoList';
import styles from '@styles/Home.module.css'
import NavBar from '@src/components/NavBar';
import Search from '@src/components/Search';

type Props = {
  searchText: string,
  repos: any[],
}

const Home:FC<Props> = (props) => {
  const [searchText, setSearchText] = useState(props.searchText);
  const [repos, setRepos] = useState(props.repos);
  const [language, setLanguage] = useState('');
  const [loading, setLoading] = useState(false);

  const onSearchTextChange = (text: string) => {
    setSearchText(text);
    if (text) {
      loadRepos(text, language);
    }
  };

  const onLanguageChange = (language) => {
    setLanguage(language);
    loadRepos(searchText, language);
  };

  const loadRepos = async (searchText, language) => {
    setLoading(true);
    const res = await searchRepos(searchText, language);
    if (res && res.data) {
      setLoading(false);
      setRepos(res.data.items);
    }
  };

  return (
    
    <>
      <NavBar />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

       
          <div className={styles.githubImg}>
            <Image src="/github-img.png" alt="Gihub Image Logo" width={400} height={280} />
          </div>
          
          <Search
            searchText={searchText}
            language={language}
            onSearchTextChange={onSearchTextChange}
            onLanguageChange={onLanguageChange}
          />
          
          <RepoList loading={loading} repos={repos} />
          
          {/* <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div> */}


        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}


export const getServerSideProps = async () => {
  const searchText = 'beer'; //default search word
  const res = await searchRepos(searchText, "");

  return {
    props: {
      searchText: searchText,
      repos: res.data.items
    }
  };
};


export default Home;