import React, { FC, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { searchRepos } from '@src/service/github';
import RepoList from '@src/components/RepoList';
import styles from '@styles/Home.module.css'
import Search from '@src/components/Search';

type Props = {
  searchText: string,
  repos: any[],
}

const Home:FC<Props> = (props) => {
  const [searchText, setSearchText] = useState(props.searchText);
  const [repos, setRepos] = useState(props.repos);
  const [loading, setLoading] = useState(false);

  const onSearchTextChange = (text: string) => {
    setSearchText(text);
    if (text) {
      loadRepos(text);
    }
  };

  const onLanguageChange = () => {
    loadRepos(searchText);
  };

  const loadRepos = async (searchText) => {
    setLoading(true);
    const res = await searchRepos(searchText);
    if (res && res.data) {
      setLoading(false);
      setRepos(res.data.items);
    }
  };

  return (
    
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

       
          <div className={styles.githubImg}>
            <Image src="/github-img.png" alt="Gihub Image Logo" width={400} height={280} />
          </div>
          
          <Search
            searchText={searchText}
            onSearchTextChange={onSearchTextChange}
            onLanguageChange={onLanguageChange}
          />
          
          <RepoList loading={loading} repos={repos} />

        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}


export const getServerSideProps = async () => {
  const searchText = 'nextjs'; //default search word
  const res = await searchRepos(searchText);

  return {
    props: {
      searchText: searchText,
      repos: res.data.items
    }
  };
};


export default Home;